In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)

In [ ]:
%pwd

'/content'

# Reading the CSV File

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Sentiment Analysis using Tweets-20230225T215534Z-001/Sentiment Analysis using Tweets/TwitterData.csv")
df.dropna()
df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu  \
0        0.0      1.000      0.000          0.0000     0.014746     0.928273   
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos Lang                                              Tweet  \
0     0.056980   en  Tripura Chief Minister Manik Saha inspected th...   
1     0.871427   en  I'd like to appreciate Ambassador Katherine Ta...   
2     0.957530   en  The ground rules of IPEF were laid out very we...   
3     0.120132   en  We also discussed progress of Indo-Pacific Eco...   
4     0.943047   en  I am delighted to share that we have made the ...   

        Tag     Score  
0  POSITIVE  0.564948  
1  POSITIVE  0.999794  
2  POSITIVE  0.999485  
3  POSITIVE  0.956361  
4  POSITIVE  0.999675

In [ ]:
# To suffel the dataset
df.sample(frac=1)

# Reseting the Index
df.reset_index(drop=True, inplace=True)

# Change the Tag to numeric values
from sklearn.preprocessing import LabelEncoder
le_tag = LabelEncoder()
df['Label'] = le_tag.fit_transform(y=df['Tag'])

df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu  \
0        0.0      1.000      0.000          0.0000     0.014746     0.928273   
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos Lang                                              Tweet  \
0     0.056980   en  Tripura Chief Minister Manik Saha inspected th...   
1     0.871427   en  I'd like to appreciate Ambassador Katherine Ta...   
2     0.957530   en  The ground rules of IPEF were laid out very we...   
3     0.120132   en  We also discussed progress of Indo-Pacific Eco...   
4     0.943047   en  I am delighted to share that we have made the ...   

        Tag     Score  Label  
0  POSITIVE  0.564948      1  
1  POSITIVE  0.999794      1  
2  POSITIVE  0.999485      1  
3  POSITIVE  0.956361      1  
4  POSITIVE  0.999675      1

In [ ]:
df = df.drop(['Lang', 'Tweet', 'Tag'], axis='columns')
df.shape

(65847, 9)

In [ ]:
df.describe()

vader_neg     vader_neu     vader_pos  vader_compound   roberta_neg  \
count  65847.000000  65847.000000  65847.000000    65847.000000  65847.000000   
mean       0.084667      0.848391      0.066941       -0.036248      0.278212   
std        0.115770      0.130022      0.088870        0.501193      0.280132   
min        0.000000      0.000000      0.000000       -0.989100      0.000601   
25%        0.000000      0.769000      0.000000       -0.458800      0.022766   
50%        0.000000      0.863000      0.030000        0.000000      0.178379   
75%        0.145000      0.959000      0.113000        0.361200      0.500133   
max        0.721000      1.000000      1.000000        0.986800      0.975476   

        roberta_neu   roberta_pos         Score         Label  
count  65847.000000  65847.000000  65847.000000  65847.000000  
mean       0.578739      0.143048      0.944641      0.363175  
std        0.263320      0.238719      0.099335      0.480918  
min        0.006210      0.001597      0.500030      0.000000  
25%        0.365045      0.015314      0.950874      0.000000  
50%        0.614623      0.033925      0.986550      0.000000  
75%        0.812929      0.121036      0.996049      1.000000  
max        0.970903      0.992736      0.999888      1.000000

In [ ]:
df.head()

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  roberta_neu  \
0        0.0      1.000      0.000          0.0000     0.014746     0.928273   
1        0.0      0.846      0.154          0.7906     0.003203     0.125370   
2        0.0      0.947      0.053          0.3384     0.001249     0.041221   
3        0.0      0.940      0.060          0.4215     0.005952     0.873916   
4        0.0      0.807      0.193          0.8519     0.002116     0.054837   

   roberta_pos     Score  Label  
0     0.056980  0.564948      1  
1     0.871427  0.999794      1  
2     0.957530  0.999485      1  
3     0.120132  0.956361      1  
4     0.943047  0.999675      1

In [ ]:
# Finding the corelation between the data
df_corr= df.corr()
df_corr

vader_neg  vader_neu  vader_pos  vader_compound  roberta_neg  \
vader_neg        1.000000  -0.744408  -0.213557       -0.727430     0.601793   
vader_neu       -0.744408   1.000000  -0.493345        0.196634    -0.349652   
vader_pos       -0.213557  -0.493345   1.000000        0.659923    -0.272368   
vader_compound  -0.727430   0.196634   0.659923        1.000000    -0.592405   
roberta_neg      0.601793  -0.349652  -0.272368       -0.592405     1.000000   
roberta_neu     -0.367960   0.422585  -0.138939        0.147454    -0.615642   
roberta_pos     -0.300312  -0.055825   0.472877        0.532527    -0.494394   
Score            0.093489  -0.096204   0.018959       -0.045245     0.180142   
Label           -0.345809   0.109116   0.290810        0.438538    -0.554596   

                roberta_neu  roberta_pos     Score     Label  
vader_neg         -0.367960    -0.300312  0.093489 -0.345809  
vader_neu          0.422585    -0.055825 -0.096204  0.109116  
vader_pos         -0.138939     0.472877  0.018959  0.290810  
vader_compound     0.147454     0.532527 -0.045245  0.438538  
roberta_neg       -0.615642    -0.494394  0.180142 -0.554596  
roberta_neu        1.000000    -0.380612 -0.272934  0.113208  
roberta_pos       -0.380612     1.000000  0.089669  0.525934  
Score             -0.272934     0.089669  1.000000 -0.062300  
Label              0.113208     0.525934 -0.062300  1.000000

### So, from here we can say that `vader_neg`	`vader_neu`	`vader_pos`	`vader_compound`	`roberta_neg`	`roberta_neu`	`roberta_pos` are independent variable and `Score` and `Label` are dependent variable





# Splitting the dataframe into Train And Test Dataframe  

In [ ]:
X = df.drop(['Label', 'Score'], axis='columns')
Y_Regg = df.Score
Y_Classify = df.Label

In [ ]:
from sklearn.model_selection import train_test_split

# For Regression
X_train_regg, X_test_regg, y_train_regg, y_test_regg = train_test_split(X, Y_Regg, test_size=0.2)

# For Clasification
X_train_classify, X_test_classify, y_train_classify, y_test_classify = train_test_split(X, Y_Classify, test_size=0.2)

In [ ]:
X_train_regg.shape

(52677, 7)

In [ ]:
X_test_regg.shape

(13170, 7)

# Multiple Linear Regression

Multiple linear regression is a statistical technique used to model the relationship between a dependent variable and multiple independent variables. It is an extension of simple linear regression, which models the relationship between a dependent variable and a single independent variable.


In [ ]:
from sklearn import datasets, linear_model, preprocessing
from sklearn.metrics import mean_squared_error, r2_score

lrm = linear_model.LinearRegression()

In [ ]:
lrm.fit(X_train_regg, y_train_regg)

LinearRegression()

In [ ]:
lrm_predict = lrm.predict(X_test_regg)
lrm_predict

array([0.91023443, 0.9171138 , 0.91007434, ..., 0.91353908, 0.93125674,
       0.94621852])

In [ ]:
y_test_regg

65493    0.951918
22660    0.951925
13052    0.941239
32195    0.997694
60635    0.991242
           ...   
4123     0.989399
62030    0.994020
52580    0.993053
31487    0.969970
8194     0.775420
Name: Score, Length: 13170, dtype: float64

In [ ]:
print("Mean Squared Error - ", mean_squared_error(y_test_regg , lrm_predict))

Mean Squared Error -  0.009264350620760758


In [ ]:
print("R-squared Value: ", r2_score(y_test_regg , lrm_predict))

R-squared Value:  0.0745740889540899


In [ ]:
print("Coeficient", lrm.coef_)
print("Intercept", lrm.intercept_)

Coeficient [-7.06433851e-01 -6.93869260e-01 -7.27874120e-01  3.63309509e-03
 -1.88025581e+03 -1.88036654e+03 -1.88026538e+03]
Intercept 1881.9634448861982


In [ ]:
 lrm.predict([[0.756, 0.244, 0.0, -0.4767, 0.91862196, 0.073102295, 0.008275842]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.99417702])

# KNN - K-Nearest Neighbors
K-Nearest Neighbors (KNN) is a simple and widely used non-parametric classification and regression algorithm. It is a supervised learning algorithm that can be used for both classification and regression problems.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


knn = KNeighborsClassifier()
knn.fit(X_train_classify, y_train_classify)

KNeighborsClassifier()

In [ ]:
knn_predict = knn.predict(X_test_classify)
print(knn_predict)

[0 0 1 ... 1 0 0]


In [ ]:
print(y_test_classify)

40033    0
8455     0
23985    1
24525    0
16134    0
        ..
33324    0
39081    1
41367    1
55865    0
54620    0
Name: Label, Length: 13170, dtype: int64


In [ ]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , knn_predict))
accuracy = accuracy_score(y_test_classify , knn_predict)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.18246013667425967
Accuracy Percentage : 81.75398633257403 %


# Random Forest

The Random Forest algorithm is a type of ensemble learning technique that combines multiple decision trees to make a prediction. In sentiment analysis, each decision tree can be trained on a subset of the available training data, with each tree making an independent prediction on the sentiment of a given piece of text. The final prediction is then made by combining the predictions of all the decision trees in the forest.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfa = RandomForestClassifier(n_estimators=100)
rfa.fit(X_train_classify, y_train_classify)

RandomForestClassifier()

In [ ]:
rfa_predicted = rfa.predict(X_test_classify)
rfa_predicted

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
print(y_test_classify)

40033    0
8455     0
23985    1
24525    0
16134    0
        ..
33324    0
39081    1
41367    1
55865    0
54620    0
Name: Label, Length: 13170, dtype: int64


In [ ]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , rfa_predicted))
accuracy = accuracy_score(y_test_classify , rfa_predicted)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.17517084282460138
Accuracy Percentage : 82.48291571753987 %


# Logistic Regression

Logistic Regression is a popular machine learning algorithm used for classification problems, where the goal is to predict whether a given input belongs to which possible classes. It is a supervised learning algorithm that models the probability of the input belonging to each class using a logistic function.

Here we are using Binary Classification since we have 2 Labels Positive and Negative

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train_classify, y_train_classify)

LogisticRegression()

In [ ]:
lr_predict = lr.predict(X_test_classify)
print(lr_predict)

[0 0 0 ... 1 1 0]


In [ ]:
print(y_test_classify)

40033    0
8455     0
23985    1
24525    0
16134    0
        ..
33324    0
39081    1
41367    1
55865    0
54620    0
Name: Label, Length: 13170, dtype: int64


In [ ]:
# Predicting the probability that how much the tweet is Negative and Positive
lr.predict_proba(X_test_classify)

array([[0.96482068, 0.03517932],
       [0.98834381, 0.01165619],
       [0.58988789, 0.41011211],
       ...,
       [0.12503609, 0.87496391],
       [0.49979597, 0.50020403],
       [0.98287716, 0.01712284]])

In [ ]:
print("Mean Squared Error - ", mean_squared_error(y_test_classify , lr_predict))
accuracy = accuracy_score(y_test_classify , lr_predict)

print("Accuracy Percentage :", accuracy*100, "%")

Mean Squared Error -  0.1780561883067578
Accuracy Percentage : 82.19438116932423 %


# Exporting the Model

In [ ]:
import pickle
models = {'lr' : lrm, 'knn' : knn, 'rf' : rfa , 'lr' : lr}

In [ ]:
with open('twittersentiment_pickle', 'wb') as file:
  pickle.dump(models, file)

# Conclusion 

Now we can conclude that the accuracy scores and MSE by using the different algorithum are - 


---



### **Regression**
1.  Linear Regression - MSE - 0.00923519554216942

### **Classification**
1.  KNN - K-Nearest Neighbors - 81.71%
2.  Random Forest - 82.83%
3.  Logistic Regression - 82.98%